/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Media } from './media';

export interface MediaMetadata {
    'id': string;
    'createdAt': string;
    'updatedAt'?: string;
    'videoCodec'?: string;
    'videoBitDepth'?: number;
    'videoLevel'?: number;
    'videoWidth'?: number;
    'videoHeight'?: number;
    'audioCodec'?: string;
    'audioSamplerate'?: number;
    'audioChannels'?: number;
    'audioChannelLayout'?: string;
    'bitrate'?: number;
    'container'?: MediaMetadataContainerEnum;
    'sizeBytes'?: number;
    'durationSeconds'?: number;
    'framerate'?: number;
    'lastScanDateTime'?: string;
    'lastModified'?: string;
    'media'?: Media;
}

export const MediaMetadataContainerEnum = {
    Mp4: 'MP4',
    Mkv: 'MKV',
    Webm: 'WEBM',
    Avi: 'AVI',
    MpegTs: 'MPEG_TS',
    Mov: 'MOV',
    Ogg: 'OGG',
    Mp3: 'MP3',
    Wav: 'WAV',
    Flac: 'FLAC',
    Aac: 'AAC',
    Opus: 'OPUS',
    Unknown: 'UNKNOWN'
} as const;

export type MediaMetadataContainerEnum = typeof MediaMetadataContainerEnum[keyof typeof MediaMetadataContainerEnum];


