/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResourceRegion } from '../models';
/**
 * VideoControllerApi - axios parameter creator
 */
export const VideoControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        directPlay: async (mediaId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('directPlay', 'mediaId', mediaId)
            const localVarPath = `/api/video/direct/{mediaId}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} xHlsToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHlsSegment: async (mediaId: string, qualityProfile: string, segmentName: string, xHlsToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('getHlsSegment', 'mediaId', mediaId)
            // verify required parameter 'qualityProfile' is not null or undefined
            assertParamExists('getHlsSegment', 'qualityProfile', qualityProfile)
            // verify required parameter 'segmentName' is not null or undefined
            assertParamExists('getHlsSegment', 'segmentName', segmentName)
            // verify required parameter 'xHlsToken' is not null or undefined
            assertParamExists('getHlsSegment', 'xHlsToken', xHlsToken)
            const localVarPath = `/api/video/hls/{mediaId}/{qualityProfile}/{segmentName}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)))
                .replace(`{${"qualityProfile"}}`, encodeURIComponent(String(qualityProfile)))
                .replace(`{${"segmentName"}}`, encodeURIComponent(String(segmentName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            if (xHlsToken != null) {
                localVarHeaderParameter['X-Hls-Token'] = String(xHlsToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VideoControllerApi - functional programming interface
 */
export const VideoControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VideoControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async directPlay(mediaId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResourceRegion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.directPlay(mediaId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideoControllerApi.directPlay']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} xHlsToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHlsSegment(mediaId: string, qualityProfile: string, segmentName: string, xHlsToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHlsSegment(mediaId, qualityProfile, segmentName, xHlsToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideoControllerApi.getHlsSegment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VideoControllerApi - factory interface
 */
export const VideoControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VideoControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        directPlay(mediaId: string, options?: RawAxiosRequestConfig): AxiosPromise<ResourceRegion> {
            return localVarFp.directPlay(mediaId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} xHlsToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHlsSegment(mediaId: string, qualityProfile: string, segmentName: string, xHlsToken: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getHlsSegment(mediaId, qualityProfile, segmentName, xHlsToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VideoControllerApi - object-oriented interface
 */
export class VideoControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} mediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public directPlay(mediaId: string, options?: RawAxiosRequestConfig) {
        return VideoControllerApiFp(this.configuration).directPlay(mediaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} mediaId 
     * @param {string} qualityProfile 
     * @param {string} segmentName 
     * @param {string} xHlsToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHlsSegment(mediaId: string, qualityProfile: string, segmentName: string, xHlsToken: string, options?: RawAxiosRequestConfig) {
        return VideoControllerApiFp(this.configuration).getHlsSegment(mediaId, qualityProfile, segmentName, xHlsToken, options).then((request) => request(this.axios, this.basePath));
    }
}

